---

- name: check if cluster is already provisioned
  stat:
    path: "{{ cluster.state.config }}"
  register: cluster_state

- block:

    - name: stopping cluster
      shell: |
        {{ oc.binary }} cluster down
      register: cluster_down

  when: cluster_state.stat.isdir is defined and cluster_state.stat.isdir
